[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
actix-rt = "2.11.0"
proptest = "1.9.0"

[profile.test.package.proptest]
opt-level = 3
